version: '1.0.{build}'
#test
image: Visual Studio 2015

platform:
  - x86
 
configuration:
  - Debug
    
environment:
  BASEDIR: c:\mylibs
  INCLUDEDIR: c:\mylibs\include\SDL2
  LIBDIR: c:\mylibs\lib
  PKG: c:\pkg

install:

# Setting directories
  - cmake --version
  - mkdir %INCLUDEDIR%
  - mkdir %LIBDIR%
  - mkdir %PKG%
  - cd %TEMP%

# Install SDL2
  - appveyor DownloadFile https://www.libsdl.org/release/SDL2-devel-2.0.7-VC.zip
  - 7z x SDL2-devel-2.0.7-VC.zip > nul
  - copy SDL2-2.0.7\include\* %INCLUDEDIR% > nul
  - copy SDL2-2.0.7\lib\x86\* %LIBDIR% > nul

# Install vcpkg
  - cd C:/pkg
  - appveyor DownloadFile https://www.github.com/Microsoft/vcpkg/archive/master.zip
  - dir
  - 7z x master.zip > nul
  - cd vcpkg-master
  - dir
  - bootstrap-vcpkg.bat
  - vcpkg integrate install
  - vcpkg install sdl2 curl
  
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo %BASEDIR%
  - echo %APPVEYOR_BUILD_FOLDER%
  - cmake
        -DCMAKE_PREFIX_PATH=%BASEDIR%
        -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --config Debug

artifacts:
  - path: Debug/main.exe
  
deploy:
   description: '$(APPVEYOR_REPO_TAG_NAME)'
   provider: GitHub
   auth_token:
       secure: wJ1OEBlw/Ro3EjUOaMtBe6WTQbVmHNhXD79e4/d5/dRdrOa2PI/lmOJzfdaZWM5N
   artifact: main.exe
   force_update: true
   on:
        appveyor_repo_tag: true 
